/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedBioticketsRouteImport } from './routes/_authenticated.biotickets'
import { Route as AuthenticatedCapacityBookingsRouteImport } from './routes/_authenticated.capacity-bookings'
import { Route as AuthenticatedContractsRouteImport } from './routes/_authenticated.contracts'
import { Route as AuthenticatedDeliveriesRouteImport } from './routes/_authenticated.deliveries'
import { Route as AuthenticatedGooCertificatesRouteImport } from './routes/_authenticated.goo-certificates'
import { Route as AuthenticatedHedgesRouteImport } from './routes/_authenticated.hedges'
import { Route as AuthenticatedMarketPricesRouteImport } from './routes/_authenticated.market-prices'
import { Route as AuthenticatedTaxTariffsRouteImport } from './routes/_authenticated.tax-tariffs'
import { Route as AuthenticatedTransfersRouteImport } from './routes/_authenticated.transfers'

const AuthenticatedDashboardLazyRouteImport = createFileRoute(
  '/_authenticated/dashboard',
)()
const AuthenticatedWorkflowLazyRouteImport = createFileRoute(
  '/_authenticated/workflow',
)()

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBioticketsRoute = AuthenticatedBioticketsRouteImport.update({
  id: '/biotickets',
  path: '/biotickets',
  getParentRoute: () => AuthenticatedRoute,
} as any).lazy(() =>
  import('./routes/_authenticated.biotickets.lazy').then((d) => d.Route),
)
const AuthenticatedCapacityBookingsRoute =
  AuthenticatedCapacityBookingsRouteImport.update({
    id: '/capacity-bookings',
    path: '/capacity-bookings',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated.capacity-bookings.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedContractsRoute = AuthenticatedContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardLazyRoute =
  AuthenticatedDashboardLazyRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated.dashboard.lazy').then((d) => d.Route),
  )
const AuthenticatedDeliveriesRoute = AuthenticatedDeliveriesRouteImport.update({
  id: '/deliveries',
  path: '/deliveries',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGooCertificatesRoute =
  AuthenticatedGooCertificatesRouteImport.update({
    id: '/goo-certificates',
    path: '/goo-certificates',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated.goo-certificates.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedHedgesRoute = AuthenticatedHedgesRouteImport.update({
  id: '/hedges',
  path: '/hedges',
  getParentRoute: () => AuthenticatedRoute,
} as any).lazy(() =>
  import('./routes/_authenticated.hedges.lazy').then((d) => d.Route),
)
const AuthenticatedMarketPricesRoute =
  AuthenticatedMarketPricesRouteImport.update({
    id: '/market-prices',
    path: '/market-prices',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTaxTariffsRoute = AuthenticatedTaxTariffsRouteImport.update({
  id: '/tax-tariffs',
  path: '/tax-tariffs',
  getParentRoute: () => AuthenticatedRoute,
} as any).lazy(() =>
  import('./routes/_authenticated.tax-tariffs.lazy').then((d) => d.Route),
)
const AuthenticatedTransfersRoute = AuthenticatedTransfersRouteImport.update({
  id: '/transfers',
  path: '/transfers',
  getParentRoute: () => AuthenticatedRoute,
} as any).lazy(() =>
  import('./routes/_authenticated.transfers.lazy').then((d) => d.Route),
)
const AuthenticatedWorkflowLazyRoute =
  AuthenticatedWorkflowLazyRouteImport.update({
    id: '/workflow',
    path: '/workflow',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated.workflow.lazy').then((d) => d.Route),
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/biotickets': typeof AuthenticatedBioticketsRoute
  '/capacity-bookings': typeof AuthenticatedCapacityBookingsRoute
  '/contracts': typeof AuthenticatedContractsRoute
  '/deliveries': typeof AuthenticatedDeliveriesRoute
  '/goo-certificates': typeof AuthenticatedGooCertificatesRoute
  '/hedges': typeof AuthenticatedHedgesRoute
  '/market-prices': typeof AuthenticatedMarketPricesRoute
  '/tax-tariffs': typeof AuthenticatedTaxTariffsRoute
  '/transfers': typeof AuthenticatedTransfersRoute
  '/dashboard': typeof AuthenticatedDashboardLazyRoute
  '/workflow': typeof AuthenticatedWorkflowLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/biotickets': typeof AuthenticatedBioticketsRoute
  '/capacity-bookings': typeof AuthenticatedCapacityBookingsRoute
  '/contracts': typeof AuthenticatedContractsRoute
  '/deliveries': typeof AuthenticatedDeliveriesRoute
  '/goo-certificates': typeof AuthenticatedGooCertificatesRoute
  '/hedges': typeof AuthenticatedHedgesRoute
  '/market-prices': typeof AuthenticatedMarketPricesRoute
  '/tax-tariffs': typeof AuthenticatedTaxTariffsRoute
  '/transfers': typeof AuthenticatedTransfersRoute
  '/dashboard': typeof AuthenticatedDashboardLazyRoute
  '/workflow': typeof AuthenticatedWorkflowLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/biotickets': typeof AuthenticatedBioticketsRoute
  '/_authenticated/capacity-bookings': typeof AuthenticatedCapacityBookingsRoute
  '/_authenticated/contracts': typeof AuthenticatedContractsRoute
  '/_authenticated/deliveries': typeof AuthenticatedDeliveriesRoute
  '/_authenticated/goo-certificates': typeof AuthenticatedGooCertificatesRoute
  '/_authenticated/hedges': typeof AuthenticatedHedgesRoute
  '/_authenticated/market-prices': typeof AuthenticatedMarketPricesRoute
  '/_authenticated/tax-tariffs': typeof AuthenticatedTaxTariffsRoute
  '/_authenticated/transfers': typeof AuthenticatedTransfersRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardLazyRoute
  '/_authenticated/workflow': typeof AuthenticatedWorkflowLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/biotickets'
    | '/capacity-bookings'
    | '/contracts'
    | '/deliveries'
    | '/goo-certificates'
    | '/hedges'
    | '/market-prices'
    | '/tax-tariffs'
    | '/transfers'
    | '/dashboard'
    | '/workflow'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/biotickets'
    | '/capacity-bookings'
    | '/contracts'
    | '/deliveries'
    | '/goo-certificates'
    | '/hedges'
    | '/market-prices'
    | '/tax-tariffs'
    | '/transfers'
    | '/dashboard'
    | '/workflow'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/biotickets'
    | '/_authenticated/capacity-bookings'
    | '/_authenticated/contracts'
    | '/_authenticated/deliveries'
    | '/_authenticated/goo-certificates'
    | '/_authenticated/hedges'
    | '/_authenticated/market-prices'
    | '/_authenticated/tax-tariffs'
    | '/_authenticated/transfers'
    | '/_authenticated/dashboard'
    | '/_authenticated/workflow'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/biotickets': {
      id: '/_authenticated/biotickets'
      path: '/biotickets'
      fullPath: '/biotickets'
      preLoaderRoute: typeof AuthenticatedBioticketsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/capacity-bookings': {
      id: '/_authenticated/capacity-bookings'
      path: '/capacity-bookings'
      fullPath: '/capacity-bookings'
      preLoaderRoute: typeof AuthenticatedCapacityBookingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/contracts': {
      id: '/_authenticated/contracts'
      path: '/contracts'
      fullPath: '/contracts'
      preLoaderRoute: typeof AuthenticatedContractsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardLazyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/deliveries': {
      id: '/_authenticated/deliveries'
      path: '/deliveries'
      fullPath: '/deliveries'
      preLoaderRoute: typeof AuthenticatedDeliveriesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/goo-certificates': {
      id: '/_authenticated/goo-certificates'
      path: '/goo-certificates'
      fullPath: '/goo-certificates'
      preLoaderRoute: typeof AuthenticatedGooCertificatesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hedges': {
      id: '/_authenticated/hedges'
      path: '/hedges'
      fullPath: '/hedges'
      preLoaderRoute: typeof AuthenticatedHedgesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/market-prices': {
      id: '/_authenticated/market-prices'
      path: '/market-prices'
      fullPath: '/market-prices'
      preLoaderRoute: typeof AuthenticatedMarketPricesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tax-tariffs': {
      id: '/_authenticated/tax-tariffs'
      path: '/tax-tariffs'
      fullPath: '/tax-tariffs'
      preLoaderRoute: typeof AuthenticatedTaxTariffsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/transfers': {
      id: '/_authenticated/transfers'
      path: '/transfers'
      fullPath: '/transfers'
      preLoaderRoute: typeof AuthenticatedTransfersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/workflow': {
      id: '/_authenticated/workflow'
      path: '/workflow'
      fullPath: '/workflow'
      preLoaderRoute: typeof AuthenticatedWorkflowLazyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedBioticketsRoute: typeof AuthenticatedBioticketsRoute
  AuthenticatedCapacityBookingsRoute: typeof AuthenticatedCapacityBookingsRoute
  AuthenticatedContractsRoute: typeof AuthenticatedContractsRoute
  AuthenticatedDeliveriesRoute: typeof AuthenticatedDeliveriesRoute
  AuthenticatedGooCertificatesRoute: typeof AuthenticatedGooCertificatesRoute
  AuthenticatedHedgesRoute: typeof AuthenticatedHedgesRoute
  AuthenticatedMarketPricesRoute: typeof AuthenticatedMarketPricesRoute
  AuthenticatedTaxTariffsRoute: typeof AuthenticatedTaxTariffsRoute
  AuthenticatedTransfersRoute: typeof AuthenticatedTransfersRoute
  AuthenticatedDashboardLazyRoute: typeof AuthenticatedDashboardLazyRoute
  AuthenticatedWorkflowLazyRoute: typeof AuthenticatedWorkflowLazyRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedBioticketsRoute: AuthenticatedBioticketsRoute,
  AuthenticatedCapacityBookingsRoute: AuthenticatedCapacityBookingsRoute,
  AuthenticatedContractsRoute: AuthenticatedContractsRoute,
  AuthenticatedDeliveriesRoute: AuthenticatedDeliveriesRoute,
  AuthenticatedGooCertificatesRoute: AuthenticatedGooCertificatesRoute,
  AuthenticatedHedgesRoute: AuthenticatedHedgesRoute,
  AuthenticatedMarketPricesRoute: AuthenticatedMarketPricesRoute,
  AuthenticatedTaxTariffsRoute: AuthenticatedTaxTariffsRoute,
  AuthenticatedTransfersRoute: AuthenticatedTransfersRoute,
  AuthenticatedDashboardLazyRoute: AuthenticatedDashboardLazyRoute,
  AuthenticatedWorkflowLazyRoute: AuthenticatedWorkflowLazyRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
