/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedContractsRouteImport } from './routes/_authenticated.contracts'
import { Route as AuthenticatedDeliveriesRouteImport } from './routes/_authenticated.deliveries'
import { Route as AuthenticatedMarketPricesRouteImport } from './routes/_authenticated.market-prices'

const AuthenticatedBioticketsLazyRouteImport = createFileRoute(
  '/_authenticated/biotickets',
)()
const AuthenticatedCapacityBookingsLazyRouteImport = createFileRoute(
  '/_authenticated/capacity-bookings',
)()
const AuthenticatedDashboardLazyRouteImport = createFileRoute(
  '/_authenticated/dashboard',
)()
const AuthenticatedGooCertificatesLazyRouteImport = createFileRoute(
  '/_authenticated/goo-certificates',
)()
const AuthenticatedHedgesLazyRouteImport = createFileRoute(
  '/_authenticated/hedges',
)()
const AuthenticatedTaxTariffsLazyRouteImport = createFileRoute(
  '/_authenticated/tax-tariffs',
)()
const AuthenticatedTransfersLazyRouteImport = createFileRoute(
  '/_authenticated/transfers',
)()
const AuthenticatedWorkflowLazyRouteImport = createFileRoute(
  '/_authenticated/workflow',
)()

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBioticketsLazyRoute =
  AuthenticatedBioticketsLazyRouteImport.update({
    id: '/biotickets',
    path: '/biotickets',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated.biotickets.lazy').then((d) => d.Route),
  )
const AuthenticatedCapacityBookingsLazyRoute =
  AuthenticatedCapacityBookingsLazyRouteImport.update({
    id: '/capacity-bookings',
    path: '/capacity-bookings',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated.capacity-bookings.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedContractsRoute = AuthenticatedContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardLazyRoute =
  AuthenticatedDashboardLazyRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated.dashboard.lazy').then((d) => d.Route),
  )
const AuthenticatedDeliveriesRoute = AuthenticatedDeliveriesRouteImport.update({
  id: '/deliveries',
  path: '/deliveries',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGooCertificatesLazyRoute =
  AuthenticatedGooCertificatesLazyRouteImport.update({
    id: '/goo-certificates',
    path: '/goo-certificates',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated.goo-certificates.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthenticatedHedgesLazyRoute = AuthenticatedHedgesLazyRouteImport.update({
  id: '/hedges',
  path: '/hedges',
  getParentRoute: () => AuthenticatedRoute,
} as any).lazy(() =>
  import('./routes/_authenticated.hedges.lazy').then((d) => d.Route),
)
const AuthenticatedMarketPricesRoute =
  AuthenticatedMarketPricesRouteImport.update({
    id: '/market-prices',
    path: '/market-prices',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTaxTariffsLazyRoute =
  AuthenticatedTaxTariffsLazyRouteImport.update({
    id: '/tax-tariffs',
    path: '/tax-tariffs',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated.tax-tariffs.lazy').then((d) => d.Route),
  )
const AuthenticatedTransfersLazyRoute =
  AuthenticatedTransfersLazyRouteImport.update({
    id: '/transfers',
    path: '/transfers',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated.transfers.lazy').then((d) => d.Route),
  )
const AuthenticatedWorkflowLazyRoute =
  AuthenticatedWorkflowLazyRouteImport.update({
    id: '/workflow',
    path: '/workflow',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated.workflow.lazy').then((d) => d.Route),
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/contracts': typeof AuthenticatedContractsRoute
  '/deliveries': typeof AuthenticatedDeliveriesRoute
  '/market-prices': typeof AuthenticatedMarketPricesRoute
  '/biotickets': typeof AuthenticatedBioticketsLazyRoute
  '/capacity-bookings': typeof AuthenticatedCapacityBookingsLazyRoute
  '/dashboard': typeof AuthenticatedDashboardLazyRoute
  '/goo-certificates': typeof AuthenticatedGooCertificatesLazyRoute
  '/hedges': typeof AuthenticatedHedgesLazyRoute
  '/tax-tariffs': typeof AuthenticatedTaxTariffsLazyRoute
  '/transfers': typeof AuthenticatedTransfersLazyRoute
  '/workflow': typeof AuthenticatedWorkflowLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/contracts': typeof AuthenticatedContractsRoute
  '/deliveries': typeof AuthenticatedDeliveriesRoute
  '/market-prices': typeof AuthenticatedMarketPricesRoute
  '/biotickets': typeof AuthenticatedBioticketsLazyRoute
  '/capacity-bookings': typeof AuthenticatedCapacityBookingsLazyRoute
  '/dashboard': typeof AuthenticatedDashboardLazyRoute
  '/goo-certificates': typeof AuthenticatedGooCertificatesLazyRoute
  '/hedges': typeof AuthenticatedHedgesLazyRoute
  '/tax-tariffs': typeof AuthenticatedTaxTariffsLazyRoute
  '/transfers': typeof AuthenticatedTransfersLazyRoute
  '/workflow': typeof AuthenticatedWorkflowLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/contracts': typeof AuthenticatedContractsRoute
  '/_authenticated/deliveries': typeof AuthenticatedDeliveriesRoute
  '/_authenticated/market-prices': typeof AuthenticatedMarketPricesRoute
  '/_authenticated/biotickets': typeof AuthenticatedBioticketsLazyRoute
  '/_authenticated/capacity-bookings': typeof AuthenticatedCapacityBookingsLazyRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardLazyRoute
  '/_authenticated/goo-certificates': typeof AuthenticatedGooCertificatesLazyRoute
  '/_authenticated/hedges': typeof AuthenticatedHedgesLazyRoute
  '/_authenticated/tax-tariffs': typeof AuthenticatedTaxTariffsLazyRoute
  '/_authenticated/transfers': typeof AuthenticatedTransfersLazyRoute
  '/_authenticated/workflow': typeof AuthenticatedWorkflowLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/contracts'
    | '/deliveries'
    | '/market-prices'
    | '/biotickets'
    | '/capacity-bookings'
    | '/dashboard'
    | '/goo-certificates'
    | '/hedges'
    | '/tax-tariffs'
    | '/transfers'
    | '/workflow'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/contracts'
    | '/deliveries'
    | '/market-prices'
    | '/biotickets'
    | '/capacity-bookings'
    | '/dashboard'
    | '/goo-certificates'
    | '/hedges'
    | '/tax-tariffs'
    | '/transfers'
    | '/workflow'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/contracts'
    | '/_authenticated/deliveries'
    | '/_authenticated/market-prices'
    | '/_authenticated/biotickets'
    | '/_authenticated/capacity-bookings'
    | '/_authenticated/dashboard'
    | '/_authenticated/goo-certificates'
    | '/_authenticated/hedges'
    | '/_authenticated/tax-tariffs'
    | '/_authenticated/transfers'
    | '/_authenticated/workflow'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/biotickets': {
      id: '/_authenticated/biotickets'
      path: '/biotickets'
      fullPath: '/biotickets'
      preLoaderRoute: typeof AuthenticatedBioticketsLazyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/capacity-bookings': {
      id: '/_authenticated/capacity-bookings'
      path: '/capacity-bookings'
      fullPath: '/capacity-bookings'
      preLoaderRoute: typeof AuthenticatedCapacityBookingsLazyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/contracts': {
      id: '/_authenticated/contracts'
      path: '/contracts'
      fullPath: '/contracts'
      preLoaderRoute: typeof AuthenticatedContractsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardLazyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/deliveries': {
      id: '/_authenticated/deliveries'
      path: '/deliveries'
      fullPath: '/deliveries'
      preLoaderRoute: typeof AuthenticatedDeliveriesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/goo-certificates': {
      id: '/_authenticated/goo-certificates'
      path: '/goo-certificates'
      fullPath: '/goo-certificates'
      preLoaderRoute: typeof AuthenticatedGooCertificatesLazyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hedges': {
      id: '/_authenticated/hedges'
      path: '/hedges'
      fullPath: '/hedges'
      preLoaderRoute: typeof AuthenticatedHedgesLazyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/market-prices': {
      id: '/_authenticated/market-prices'
      path: '/market-prices'
      fullPath: '/market-prices'
      preLoaderRoute: typeof AuthenticatedMarketPricesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tax-tariffs': {
      id: '/_authenticated/tax-tariffs'
      path: '/tax-tariffs'
      fullPath: '/tax-tariffs'
      preLoaderRoute: typeof AuthenticatedTaxTariffsLazyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/transfers': {
      id: '/_authenticated/transfers'
      path: '/transfers'
      fullPath: '/transfers'
      preLoaderRoute: typeof AuthenticatedTransfersLazyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/workflow': {
      id: '/_authenticated/workflow'
      path: '/workflow'
      fullPath: '/workflow'
      preLoaderRoute: typeof AuthenticatedWorkflowLazyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedContractsRoute: typeof AuthenticatedContractsRoute
  AuthenticatedDeliveriesRoute: typeof AuthenticatedDeliveriesRoute
  AuthenticatedMarketPricesRoute: typeof AuthenticatedMarketPricesRoute
  AuthenticatedBioticketsLazyRoute: typeof AuthenticatedBioticketsLazyRoute
  AuthenticatedCapacityBookingsLazyRoute: typeof AuthenticatedCapacityBookingsLazyRoute
  AuthenticatedDashboardLazyRoute: typeof AuthenticatedDashboardLazyRoute
  AuthenticatedGooCertificatesLazyRoute: typeof AuthenticatedGooCertificatesLazyRoute
  AuthenticatedHedgesLazyRoute: typeof AuthenticatedHedgesLazyRoute
  AuthenticatedTaxTariffsLazyRoute: typeof AuthenticatedTaxTariffsLazyRoute
  AuthenticatedTransfersLazyRoute: typeof AuthenticatedTransfersLazyRoute
  AuthenticatedWorkflowLazyRoute: typeof AuthenticatedWorkflowLazyRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedContractsRoute: AuthenticatedContractsRoute,
  AuthenticatedDeliveriesRoute: AuthenticatedDeliveriesRoute,
  AuthenticatedMarketPricesRoute: AuthenticatedMarketPricesRoute,
  AuthenticatedBioticketsLazyRoute: AuthenticatedBioticketsLazyRoute,
  AuthenticatedCapacityBookingsLazyRoute:
    AuthenticatedCapacityBookingsLazyRoute,
  AuthenticatedDashboardLazyRoute: AuthenticatedDashboardLazyRoute,
  AuthenticatedGooCertificatesLazyRoute: AuthenticatedGooCertificatesLazyRoute,
  AuthenticatedHedgesLazyRoute: AuthenticatedHedgesLazyRoute,
  AuthenticatedTaxTariffsLazyRoute: AuthenticatedTaxTariffsLazyRoute,
  AuthenticatedTransfersLazyRoute: AuthenticatedTransfersLazyRoute,
  AuthenticatedWorkflowLazyRoute: AuthenticatedWorkflowLazyRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
