CREATE TABLE physical_deliveries (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    contract_id UUID NOT NULL REFERENCES contracts(id),
    contract_instance_id VARCHAR(120) NOT NULL,
    book_type book_type_enum NOT NULL,
    supply_month DATE NOT NULL,
    year SMALLINT GENERATED ALWAYS AS (EXTRACT(YEAR FROM supply_month)) STORED,
    status report_status_enum NOT NULL DEFAULT 'Pending - No Invoice',
    trader_comment TEXT,
    balancing_group VARCHAR(50),
    trading_area VARCHAR(20),
    capacity_mw NUMERIC(15,6),
    volume_nominated_mwh NUMERIC(15,6),
    volume_realised_mwh NUMERIC(15,6),
    volume_corr1_mwh NUMERIC(15,6),
    volume_corr2_mwh NUMERIC(15,6),
    volume_intercompany_mwh NUMERIC(15,6),
    volume_mwh NUMERIC(15,6),
    price_mechanism gas_price_mech_enum,
    start_day DATE,
    start_hour TIME,
    end_day DATE,
    end_hour TIME,
    start_datetime TIMESTAMPTZ,
    end_datetime TIMESTAMPTZ,
    hours NUMERIC(6,2),
    delivery_type delivery_type_enum,
    product product_type_enum,
    country VARCHAR(100),
    contract_type contract_type_enum,
    cost_eur_mwh NUMERIC(12,6),
    revenue_eur NUMERIC(15,2),
    handling_fee_eur_mwh NUMERIC(12,6),
    handling_fee_eur NUMERIC(15,2),
    broker_fee_eur_mwh NUMERIC(12,6),
    broker_fee_eur NUMERIC(15,2),
    tax_eur_mwh NUMERIC(12,6),
    tax_eur NUMERIC(15,2),
    tso_tariff_eur_mwh NUMERIC(12,6),
    tso_tariff_eur NUMERIC(15,2),
    dso_tariff_eur_mwh NUMERIC(12,6),
    dso_tariff_eur_day NUMERIC(12,6),
    dso_tariff_eur NUMERIC(15,2),
    fixed_extra_eur NUMERIC(15,2),
    adm_fee_eur_mwh NUMERIC(12,6),
    adm_fee_eur NUMERIC(15,2),
    bal_fee_eur_mwh NUMERIC(12,6),
    bal_fee_eur NUMERIC(15,2),
    shipping_cost_eur_mwh NUMERIC(12,6),
    shipping_cost_eur NUMERIC(15,2),
    extra_eur NUMERIC(15,2),
    extra_note TEXT,
    subtotal_eur NUMERIC(15,2),
    agg_tax_eur NUMERIC(15,2),
    agg_tariff_eur NUMERIC(15,2),
    vat_pct NUMERIC(5,4),
    vat_eur NUMERIC(15,2),
    invoice_amount_eur NUMERIC(15,2),
    quality VARCHAR(50),
    certification_quality VARCHAR(100),
    client_type client_type_enum,
    counterparty_segment segment_enum,
    sending_shipper VARCHAR(50),
    receiving_shipper VARCHAR(50),
    shipper_code VARCHAR(50),
    sourcing_center VARCHAR(50),
    sales_center VARCHAR(50),
    delivery_month DATE,
    booking_month DATE,
    document_no VARCHAR(50),
    invoice_date DATE,
    payment_date_forecast DATE,
    payment_date_manual DATE,
    payment_date DATE,
    bilagsdato DATE,
    payment_diff_days SMALLINT,
    comment TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    CONSTRAINT uk_contract_instance UNIQUE (contract_id, contract_instance_id, book_type)
);

CREATE INDEX idx_deliveries_contract_month ON physical_deliveries(contract_id, supply_month DESC);
CREATE INDEX idx_deliveries_book_type ON physical_deliveries(book_type, supply_month);
CREATE INDEX idx_deliveries_status ON physical_deliveries(status);

CREATE TABLE capacity_bookings (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    contract_id UUID NOT NULL REFERENCES contracts(id),
    contract_instance_id VARCHAR(120) NOT NULL,
    supply_month DATE NOT NULL,
    balancing_group VARCHAR(50),
    counterparty_id UUID REFERENCES counterparties(id),
    price_mechanism capacity_price_mech_enum,
    start_area VARCHAR(20),
    end_area VARCHAR(20),
    ship_fix VARCHAR(50),
    border_point VARCHAR(100),
    start_day DATE,
    start_hour TIME,
    end_day DATE,
    end_hour TIME,
    start_datetime TIMESTAMPTZ,
    end_datetime TIMESTAMPTZ,
    hours NUMERIC(6,2),
    capacity_mw NUMERIC(15,6),
    capacity_price_eur_mwh NUMERIC(12,6),
    capacity_cost_eur NUMERIC(15,2),
    weighted_cost_eur NUMERIC(15,2),
    comments TEXT,
    invoicing_mechanism invoicing_mech_enum,
    payment_mechanism payment_mech_enum,
    days_to_invoice_after_delivery SMALLINT,
    days_to_payment_after_invoice SMALLINT,
    invoice_date DATE,
    payment_date DATE,
    payment_week SMALLINT,
    payment_month SMALLINT,
    payment_year SMALLINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    CONSTRAINT uk_capacity_instance UNIQUE (contract_id, contract_instance_id)
);

CREATE INDEX idx_capacity_contract_month ON capacity_bookings(contract_id, supply_month);
CREATE INDEX idx_capacity_start_end_area ON capacity_bookings(start_area, end_area);

CREATE TABLE transfers (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    contract_id UUID NOT NULL REFERENCES contracts(id),
    contract_instance_id VARCHAR(120) NOT NULL,
    supply_month DATE NOT NULL,
    balancing_group VARCHAR(50),
    counterparty_id UUID REFERENCES counterparties(id),
    trading_area VARCHAR(20),
    capacity_mw NUMERIC(15,6),
    booked_capacity_mw NUMERIC(15,6),
    volume_mwh NUMERIC(15,6),
    transfer_balancing_effect NUMERIC(15,6),
    balancing_effect_mwh NUMERIC(15,6),
    commitment_date DATE,
    signing_date DATE,
    start_day DATE,
    start_hour TIME,
    end_day DATE,
    end_hour TIME,
    start_datetime TIMESTAMPTZ,
    end_datetime TIMESTAMPTZ,
    hours NUMERIC(6,2),
    delivery_type delivery_type_enum,
    price_mechanism gas_price_mech_enum,
    transport_cost_eur_mwh NUMERIC(12,6),
    capacity_cost_eur_mwh NUMERIC(12,6),
    transport_cost_eur NUMERIC(15,2),
    capacity_cost_eur NUMERIC(15,2),
    extras_eur NUMERIC(15,2),
    extra_note TEXT,
    subtotal_amount_eur NUMERIC(15,2),
    vat_pct NUMERIC(5,4),
    vat_eur NUMERIC(15,2),
    invoicing_amount_eur NUMERIC(15,2),
    quality VARCHAR(50),
    receiving_shipper VARCHAR(50),
    shipper_code VARCHAR(50),
    client_type client_type_enum,
    comments TEXT,
    trader_comment TEXT,
    status report_status_enum,
    document_no VARCHAR(50),
    invoice_date DATE,
    payment_date_forecast DATE,
    payment_week SMALLINT,
    payment_month SMALLINT,
    payment_year SMALLINT,
    payment_date_manual DATE,
    payment_date DATE,
    bilagsdato DATE,
    match_mwh NUMERIC(15,6),
    match_eur NUMERIC(15,2),
    corr1_mwh NUMERIC(15,6),
    corr2_mwh NUMERIC(15,6),
    corr3_mwh NUMERIC(15,6),
    created_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    CONSTRAINT uk_transfer_instance UNIQUE (contract_id, contract_instance_id)
);

CREATE INDEX idx_transfers_contract_month ON transfers(contract_id, supply_month);

CREATE TABLE bioticket_deliveries (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    contract_id UUID NOT NULL REFERENCES contracts(id),
    contract_instance_id VARCHAR(120) NOT NULL,
    book_type book_type_enum NOT NULL,
    contract_month DATE NOT NULL,
    start_day DATE,
    end_day DATE,
    volume_nominated_ton NUMERIC(15,6),
    volume_realised_ton NUMERIC(15,6),
    volume_ton NUMERIC(15,6),
    cost_eur_ton NUMERIC(12,6),
    revenue_eur NUMERIC(15,2),
    extra_eur NUMERIC(15,2),
    extra_note TEXT,
    subtotal_eur NUMERIC(15,2),
    vat_pct NUMERIC(5,4),
    vat_eur NUMERIC(15,2),
    invoice_amount_eur NUMERIC(15,2),
    counterparty_segment segment_enum,
    sourcing_center VARCHAR(50),
    sales_center VARCHAR(50),
    product VARCHAR(50) NOT NULL DEFAULT 'Tickets',
    country VARCHAR(100),
    contract_type contract_type_enum,
    invoicing_mechanism invoicing_mech_enum,
    payment_mechanism payment_mech_enum,
    days_to_invoice_after_delivery SMALLINT,
    days_to_payment_after_invoice SMALLINT,
    invoice_date DATE,
    payment_date_forecast DATE,
    year SMALLINT,
    delivery_month DATE,
    booking_month DATE,
    document_no VARCHAR(50),
    payment_date_manual DATE,
    payment_date DATE,
    status report_status_enum NOT NULL DEFAULT 'Pending - No Invoice',
    trader_comment TEXT,
    comment TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    CONSTRAINT uk_bioticket_instance UNIQUE (contract_id, contract_instance_id, book_type)
);

CREATE INDEX idx_bioticket_contract_month ON bioticket_deliveries(contract_id, contract_month);

CREATE TABLE tax_tariffs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    contract_id UUID NOT NULL REFERENCES contracts(id),
    counterparty_id UUID REFERENCES counterparties(id),
    period_start DATE NOT NULL,
    period_end DATE NOT NULL,
    tax_local_cur_mwh NUMERIC(12,6),
    tso_local_cur_mwh NUMERIC(12,6),
    dso_local_cur_mwh NUMERIC(12,6),
    dso_tariff_local_cur_day NUMERIC(12,6),
    adm_fee_local_cur_mwh NUMERIC(12,6),
    bal_fee_local_cur_mwh NUMERIC(12,6),
    currency CHAR(3) NOT NULL DEFAULT 'SEK',
    created_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    CONSTRAINT uk_tax_period UNIQUE (contract_id, period_start, period_end)
);

CREATE INDEX idx_tax_contract ON tax_tariffs(contract_id, period_start);

CREATE TABLE hedges (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    contract_id UUID NOT NULL REFERENCES contracts(id),
    month DATE NOT NULL,
    hedge_amount_mwh NUMERIC(15,6),
    hedge_price_eur_mwh NUMERIC(12,6),
    created_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    CONSTRAINT uk_hedge_month UNIQUE (contract_id, month)
);

CREATE INDEX idx_hedges_contract ON hedges(contract_id, month);

