version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Europe/Copenhagen
    groups:
      minor-and-patch:
        patterns: ["*"]
        update-types: [minor, patch]

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Europe/Copenhagen
    groups:
      minor-and-patch:
        patterns: ["*"]
        update-types: [minor, patch]

  - package-ecosystem: npm
    directory: /src/Frontend
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Europe/Copenhagen
    groups:
      minor-and-patch:
        patterns: ["*"]
        update-types: [minor, patch]

  - package-ecosystem: npm
    directory: /tests/e2e
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Europe/Copenhagen
    groups:
      minor-and-patch:
        patterns: ["*"]
        update-types: [minor, patch]

  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Europe/Copenhagen
    groups:
      minor-and-patch:
        patterns: ["*"]
        update-types: [minor, patch]

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Europe/Copenhagen
    groups:
      minor-and-patch:
        patterns: ["*"]
        update-types: [minor, patch]

  - package-ecosystem: terraform
    directory: /infra/terraform
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: Europe/Copenhagen
    groups:
      minor-and-patch:
        patterns: ["*"]
        update-types: [minor, patch]
