using System.Text.Json.Serialization;
using Tradebook.Core.DTOs;
using Tradebook.Core.Analytics;
using Tradebook.Api.Features.Analytics;
using Tradebook.Core.Domain.ValueObjects.Ids;
using Tradebook.Core.Domain.ValueObjects.Money;

namespace Tradebook.Api;

[JsonSourceGenerationOptions(PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase, DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull)]
[JsonSerializable(typeof(CreatePhysicalDeliveryRequest))]
[JsonSerializable(typeof(CreatePhysicalDeliveryResponse))]
[JsonSerializable(typeof(PhysicalDeliveryDetailsDto))]
[JsonSerializable(typeof(GetDeliveryHistoryRequest))]
[JsonSerializable(typeof(GetDeliveryHistoryResponse))]
[JsonSerializable(typeof(UpdatePhysicalDeliveryRequest))]
[JsonSerializable(typeof(DeletePhysicalDeliveryRequest))]
[JsonSerializable(typeof(CreateContractRequest))]
[JsonSerializable(typeof(UpdateContractRequest))]
[JsonSerializable(typeof(ContractDetailsDto))]
[JsonSerializable(typeof(GetContractHistoryRequest))]
[JsonSerializable(typeof(GetContractHistoryResponse))]
[JsonSerializable(typeof(DeactivateContractRequest))]
[JsonSerializable(typeof(CreateCapacityBookingRequest))]
[JsonSerializable(typeof(UpdateCapacityBookingRequest))]
[JsonSerializable(typeof(CapacityBookingDetailsDto))]
[JsonSerializable(typeof(GetCapacityBookingHistoryRequest))]
[JsonSerializable(typeof(GetCapacityBookingHistoryResponse))]
[JsonSerializable(typeof(DeleteCapacityBookingRequest))]
[JsonSerializable(typeof(CreateTransferRequest))]
[JsonSerializable(typeof(UpdateTransferRequest))]
[JsonSerializable(typeof(TransferDetailsDto))]
[JsonSerializable(typeof(GetTransferHistoryRequest))]
[JsonSerializable(typeof(GetTransferHistoryResponse))]
[JsonSerializable(typeof(CancelTransferRequest))]
[JsonSerializable(typeof(CreateBioticketRequest))]
[JsonSerializable(typeof(UpdateBioticketRequest))]
[JsonSerializable(typeof(BioticketDetailsDto))]
[JsonSerializable(typeof(GetBioticketHistoryRequest))]
[JsonSerializable(typeof(GetBioticketHistoryResponse))]
[JsonSerializable(typeof(CancelBioticketRequest))]
[JsonSerializable(typeof(CreateGooCertificateTransactionRequest))]
[JsonSerializable(typeof(UpdateGooCertificateTransactionRequest))]
[JsonSerializable(typeof(GooCertificateTransactionDetailsDto))]
[JsonSerializable(typeof(GetGooCertificateHistoryRequest))]
[JsonSerializable(typeof(GetGooCertificateHistoryResponse))]
[JsonSerializable(typeof(RequestGooBatchExportRequest))]
[JsonSerializable(typeof(DeleteGooCertificateTransactionRequest))]
[JsonSerializable(typeof(UpsertMarketPriceRequest))]
[JsonSerializable(typeof(MarketPriceDetailsDto))]
[JsonSerializable(typeof(GetMarketPriceHistoryRequest))]
[JsonSerializable(typeof(GetMarketPriceHistoryResponse))]
[JsonSerializable(typeof(DeleteMarketPriceRequest))]
[JsonSerializable(typeof(CreateTaxTariffRequest))]
[JsonSerializable(typeof(UpdateTaxTariffRequest))]
[JsonSerializable(typeof(TaxTariffDetailsDto))]
[JsonSerializable(typeof(GetTaxTariffHistoryRequest))]
[JsonSerializable(typeof(GetTaxTariffHistoryResponse))]
[JsonSerializable(typeof(DeleteTaxTariffRequest))]
[JsonSerializable(typeof(CreateHedgeRequest))]
[JsonSerializable(typeof(UpdateHedgeRequest))]
[JsonSerializable(typeof(HedgeDetailsDto))]
[JsonSerializable(typeof(GetHedgeHistoryRequest))]
[JsonSerializable(typeof(GetHedgeHistoryResponse))]
[JsonSerializable(typeof(DeleteHedgeRequest))]
[JsonSerializable(typeof(LoginRequest))]
[JsonSerializable(typeof(LoginResponse))]
[JsonSerializable(typeof(EntityChangedEventDto))]
[JsonSerializable(typeof(GetEventsSinceResponse))]
[JsonSerializable(typeof(JsonQueryAst))]
[JsonSerializable(typeof(AnalyticsQueryResponse))]
[JsonSerializable(typeof(SaveDashboardRequest))]
[JsonSerializable(typeof(SaveDashboardResponse))]
[JsonSerializable(typeof(ProblemDetailsResponse))]
[JsonSerializable(typeof(FastEndpoints.ErrorResponse))]
[JsonSerializable(typeof(Guid))]
[JsonSerializable(typeof(decimal))]
[JsonSerializable(typeof(ContractId))]
[JsonSerializable(typeof(DeliveryId))]
[JsonSerializable(typeof(CapacityBookingId))]
[JsonSerializable(typeof(TransferId))]
[JsonSerializable(typeof(BioticketDeliveryId))]
[JsonSerializable(typeof(CounterpartyId))]
[JsonSerializable(typeof(CompanyId))]
[JsonSerializable(typeof(TradingPointId))]
[JsonSerializable(typeof(TaxTariffId))]
[JsonSerializable(typeof(HedgeId))]
[JsonSerializable(typeof(MarketPriceId))]
[JsonSerializable(typeof(CapacityPriceIndexId))]
[JsonSerializable(typeof(GooCertificateTransactionId))]
[JsonSerializable(typeof(InvoiceLineItemId))]
[JsonSerializable(typeof(UserId))]
[JsonSerializable(typeof(DashboardId))]
[JsonSerializable(typeof(Tradebook.Core.Domain.ValueObjects.Ids.EventId))]
[JsonSerializable(typeof(AuditLogId))]
[JsonSerializable(typeof(Price))]
[JsonSerializable(typeof(Quantity))]
[JsonSerializable(typeof(Amount))]
public partial class AppJsonSerializerContext : JsonSerializerContext;
