<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>
    <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Protocols.MessagePack" />
    <PackageReference Include="Aspire.Hosting.Testing" />
    <PackageReference Include="Testcontainers.PostgreSql" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.analyzers" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Backend\src\Tradebook.Api\Tradebook.Api.csproj" />
    <ProjectReference Include="..\..\src\Backend\src\Tradebook.Core\Tradebook.Core.csproj" />
    <ProjectReference Include="..\..\src\Backend\src\Tradebook.Infrastructure\Tradebook.Infrastructure.csproj" />
    <ProjectReference
      Include="..\..\src\Aspire\Tradebook.AppHost\Tradebook.AppHost.csproj"
      Aliases="apphost"
    />
  </ItemGroup>
</Project>
