<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" />
    <PackageReference Include="TypeGen" />
    <PackageReference Include="Vogen" />
    <PackageReference Include="YamlDotNet" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="SemanticModels\**\*.yaml" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
