namespace Tradebook.Core.Analytics;

public sealed class SemanticModelConfig { public string Version { get; set; } = ""; public SemanticModelRoot SemanticModel { get; set; } = new(); }
public sealed class SemanticModelRoot { public string Name { get; set; } = ""; public string Description { get; set; } = ""; public string TargetEntity { get; set; } = ""; public List<EntityDefinition> Entities { get; set; } = []; public List<JoinDefinition> Joins { get; set; } = []; public List<DimensionDefinition> Dimensions { get; set; } = []; public List<MeasureDefinition> Measures { get; set; } = []; public List<MetricDefinition> Metrics { get; set; } = []; }
public sealed class EntityDefinition { public string Name { get; set; } = ""; public string Table { get; set; } = ""; public string PrimaryKey { get; set; } = ""; public List<string> Columns { get; set; } = []; public string Description { get; set; } = ""; }
public sealed class JoinDefinition { public string Name { get; set; } = ""; public string LeftEntity { get; set; } = ""; public string RightEntity { get; set; } = ""; public string JoinType { get; set; } = ""; public string Relationship { get; set; } = ""; public string LeftColumn { get; set; } = ""; public string RightColumn { get; set; } = ""; }
public sealed class DimensionDefinition { public string Name { get; set; } = ""; public string Entity { get; set; } = ""; public string Type { get; set; } = ""; public string Sql { get; set; } = ""; public string? JsonbKey { get; set; } public string? Description { get; set; } public List<string>? Granularity { get; set; } }
public sealed class MeasureDefinition { public string Name { get; set; } = ""; public string Entity { get; set; } = ""; public string Type { get; set; } = ""; public string Sql { get; set; } = ""; public string? Description { get; set; } public string? Format { get; set; } }
public sealed class MetricDefinition { public string Name { get; set; } = ""; public string Description { get; set; } = ""; public string Expression { get; set; } = ""; public string? Format { get; set; } }
public sealed record JoinChainStep(JoinDefinition Join, string NewEntity);
