<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\Tradebook.Core\Tradebook.Core.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Tradebook.UnitTests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Bogus" />
    <PackageReference Include="Dapper" />
    <PackageReference Include="dbup-postgresql" />
    <PackageReference Include="Npgsql" />
    <PackageReference Include="Microsoft.Extensions.Caching.Hybrid" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Options" />
    <PackageReference Include="Riok.Mapperly" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource
      Include="..\..\..\Database\Migrations\*.sql"
      LogicalName="Tradebook.Database.Migrations.%(Filename)%(Extension)"
    />
  </ItemGroup>
</Project>
