<Project Sdk="Aspire.AppHost.Sdk/13.4.6">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" />
    <PackageReference Include="Aspire.Hosting.JavaScript" />
    <PackageReference Include="Aspire.Hosting.PostgreSQL" />
    <ProjectReference Include="..\..\Backend\src\Tradebook.Api\Tradebook.Api.csproj" />
    <ProjectReference Include="..\..\Backend\src\Tradebook.Workers\Tradebook.Workers.csproj" />
  </ItemGroup>
</Project>
